"""Generic DCF v2 immutable-generation and action-context core."""

from .capabilities import (
    CAPABILITY_REGISTRY,
    CapabilityClass,
    CapabilityPolicy,
    capability_policy,
)
from .collectors import CollectionError, ProjectLayout
from .events import acknowledge_events, enqueue_event, event_root, pending_events
from .jspace import (
    JSPACE_AUTHORIZATION_SCHEMA_VERSION,
    JSPACE_EXPANSION_ERROR,
    JSPACE_SCHEMA_VERSION,
    TASK_CONTEXT_CAPSULE_SCHEMA_VERSION,
    JSpaceCompileError,
    canonical_contract_bytes,
    compile_jspace_contract,
    compile_task_context_capsule,
    verify_contract_freshness,
    write_immutable_contract,
)
from .models import (
    CapabilitySnapshot,
    DcfSnapshot,
    GenerationFile,
    GenerationManifest,
    GenerationPointer,
    QueryResponse,
    SafetyBoundary,
    StatusResponse,
    TemporalBoundary,
)
from .query import (
    DEFAULT_HARD_STALE_CAPABILITIES,
    FreshnessBlocked,
    InvalidQuery,
    UnknownCapability,
    query_capability,
)
from .runtime import DcfRuntime
from .storage import (
    GenerationStore,
    GenerationTransactionError,
    GenerationUnavailable,
    atomic_write_bytes,
    atomic_write_json,
    canonical_json_bytes,
    path_reference,
    sha256_bytes,
    sha256_file,
    utc_now,
)

__all__ = [
    "CAPABILITY_REGISTRY",
    "DEFAULT_HARD_STALE_CAPABILITIES",
    "JSPACE_AUTHORIZATION_SCHEMA_VERSION",
    "JSPACE_EXPANSION_ERROR",
    "JSPACE_SCHEMA_VERSION",
    "TASK_CONTEXT_CAPSULE_SCHEMA_VERSION",
    "CapabilityClass",
    "CapabilityPolicy",
    "CapabilitySnapshot",
    "CollectionError",
    "DcfRuntime",
    "DcfSnapshot",
    "FreshnessBlocked",
    "GenerationFile",
    "GenerationManifest",
    "GenerationPointer",
    "GenerationStore",
    "GenerationTransactionError",
    "GenerationUnavailable",
    "InvalidQuery",
    "JSpaceCompileError",
    "QueryResponse",
    "ProjectLayout",
    "SafetyBoundary",
    "StatusResponse",
    "TemporalBoundary",
    "UnknownCapability",
    "acknowledge_events",
    "atomic_write_bytes",
    "atomic_write_json",
    "canonical_contract_bytes",
    "canonical_json_bytes",
    "capability_policy",
    "compile_jspace_contract",
    "compile_task_context_capsule",
    "enqueue_event",
    "event_root",
    "path_reference",
    "pending_events",
    "query_capability",
    "sha256_bytes",
    "sha256_file",
    "utc_now",
    "verify_contract_freshness",
    "write_immutable_contract",
]
